version: '3.8'

services:
  nats:
    image: nats:latest
    container_name: toyserver_nats
    ports:
      - "4222:4222"
      - "8222:8222"
    restart: always

  redis:
    image: redis:latest
    container_name: toyserver_redis
    ports:
      - "6379:6379"
    restart: always
